# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_study', '0002_auto_20171019_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default='S', max_length=1, verbose_name='Shirt Size'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
    ]
