# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_study', '0003_auto_20171020_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
    ]
