# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_study', '0006_auto_20171020_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horn_length', models.IntegerField(verbose_name='horn lenth')),
            ],
            options={
                'ordering': ['horn_length'],
                'verbose_name_plural': 'oxen',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(auto_now=True, verbose_name='Birth Date'),
        ),
    ]
