# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_study', '0007_auto_20171024_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('school', models.CharField(max_length=100, verbose_name='school')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='Restrant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_study.Place')),
                ('serves_hot_dogs', models.BooleanField(default=False)),
                ('serve_pizza', models.BooleanField(default=False)),
            ],
            bases=('model_study.place',),
        ),
    ]
