# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50, verbose_name='Branch Name')),
                ('project_name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('update_date', models.DateField(auto_now=True, verbose_name='UpDate Date')),
            ],
        ),
        migrations.CreateModel(
            name='LavaServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('server_hostname', models.CharField(max_length=50, verbose_name='Host Name')),
                ('server_ip', models.GenericIPAddressField(verbose_name='Server IP Address')),
                ('submit_user_name', models.CharField(max_length=30, verbose_name='Submiter user name')),
                ('submit_user_token', models.CharField(max_length=200, verbose_name='Submit user token')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managers_mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('task_type', models.CharField(choices=[('verify', 'verify'), ('daily', 'daily'), ('manual', 'manual')], max_length=20, verbose_name='Task Type')),
                ('device_type', models.CharField(max_length=50, verbose_name='Device Type')),
                ('stop_flag', models.BooleanField(default=False, verbose_name='Stopping Test')),
                ('branch_project_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lava_submission.BranchProjectInfo')),
                ('device_in_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lava_submission.LavaServerInfo')),
            ],
        ),
    ]
