# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lava_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchprojectinfo',
            name='branch_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lava_submission.VerifyBranchType'),
        ),
    ]
