# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyprojectinfo',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
    ]
