# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lava_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchprojectinfo',
            name='branch_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lava_submission.VerifyBranchType'),
        ),
    ]
