# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava_submission', '0002_auto_20171027_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyprojectinfo',
            name='device_type',
            field=models.CharField(max_length=50, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='verifyprojectinfo',
            name='task_type',
            field=models.CharField(choices=[('verify', 'verify'), ('daily', 'daily'), ('manual', 'manual')], max_length=20, verbose_name='Task Type'),
        ),
    ]
