# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lava_submission', '0002_verifyprojectinfo_modify_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyBranchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Branch Type')),
                ('url_str', models.URLField(verbose_name='Verify URL')),
            ],
        ),
        migrations.AddField(
            model_name='verifyprojectinfo',
            name='branch_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lava_submission.VerifyBranchType'),
            preserve_default=False,
        ),
    ]
