# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava_submission', '0002_auto_20171102_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyprojectinfo',
            name='repository',
            field=models.CharField(default='', max_length=200, verbose_name='repository'),
            preserve_default=False,
        ),
    ]
