# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lava_submission', '0003_auto_20171101_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchprojectinfo',
            name='branch_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lava_submission.VerifyBranchType'),
            preserve_default=False,
        ),
    ]
