# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lava_submission', '0003_verifyprojectinfo_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50, verbose_name='branch')),
                ('project', models.CharField(max_length=50, verbose_name='project')),
                ('buildid', models.CharField(max_length=50, verbose_name='buildid')),
                ('submiter', models.CharField(max_length=50, verbose_name='submiter')),
                ('verify_url', models.CharField(max_length=200, verbose_name='verify_url')),
                ('gerrit_id', models.CharField(max_length=50, verbose_name='gerrit_id')),
                ('port', models.CharField(max_length=50, verbose_name='port')),
                ('compile_user', models.CharField(max_length=50, verbose_name='compile_user')),
                ('module', models.CharField(max_length=50, verbose_name='module')),
                ('testcase', models.CharField(max_length=50, verbose_name='testcase')),
                ('manual_testcase', models.CharField(max_length=50, verbose_name='manual_testcase')),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone_number')),
                ('test_description', models.CharField(max_length=50, verbose_name='test_description')),
                ('project_num', models.CharField(max_length=50, verbose_name='project_num')),
                ('test_task_type', models.CharField(max_length=50, verbose_name='test_task_type')),
                ('bugid', models.CharField(max_length=200, verbose_name='bugid to gerrit')),
                ('repository', models.CharField(max_length=100, verbose_name='code repository')),
                ('device_type', models.CharField(max_length=50, verbose_name='device type')),
                ('from_verify_server_time', models.DateTimeField(auto_now=True)),
                ('submit_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='submit time')),
                ('status', models.IntegerField(choices=[(0, 'No submit'), (1, 'Submitted')], default=0, verbose_name='submit status')),
                ('filted', models.BooleanField(default=False)),
                ('submitted_result', models.IntegerField(choices=[(0, 'Submitted successfully'), (1, 'Submitted failed')], default=0, help_text='submitted task can be successfully or fail', verbose_name='submitted result')),
                ('submitted_fail_reason', models.CharField(help_text='submitted fail reason, if fail you can input some words mark it', max_length=100, verbose_name='submitted fail reason')),
                ('resubmit_count', models.IntegerField(default=1, verbose_name='resubmit count')),
                ('last_job_status', models.IntegerField(default=0, verbose_name='last lava job status')),
                ('verify_project_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lava_submission.VerifyProjectInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TestJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(default=None, max_length=10, verbose_name='jobid')),
                ('job_status', models.CharField(default='Submitted', max_length=50, verbose_name='job status')),
                ('testcase', models.CharField(default='default', help_text='formate ${casename},${casename}', max_length=200, verbose_name='buildid')),
                ('testcase_result', models.CharField(default='default', help_text='formate ${casename},${result}', max_length=200, verbose_name='testcase result')),
                ('submitted_time', models.DateTimeField(auto_now=True, verbose_name='submitted time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='end time')),
                ('check_or_not', models.BooleanField(default=True, verbose_name='Check job or not')),
                ('collect_infos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_collector.CollectInfos')),
            ],
        ),
    ]
