# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50, verbose_name='branch')),
                ('project', models.CharField(max_length=50, verbose_name='project')),
                ('buildid', models.CharField(max_length=50, verbose_name='buildid')),
                ('submiter', models.CharField(max_length=50, verbose_name='submiter')),
                ('verify_url', models.CharField(max_length=50, verbose_name='verify_url')),
                ('gerrit_id', models.CharField(max_length=50, verbose_name='gerrit_id')),
                ('port', models.CharField(max_length=50, verbose_name='port')),
                ('compile_user', models.CharField(max_length=50, verbose_name='compile_user')),
                ('module', models.CharField(max_length=50, verbose_name='module')),
                ('testcase', models.CharField(max_length=50, verbose_name='testcase')),
                ('manual_testcase', models.CharField(max_length=50, verbose_name='manual_testcase')),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone_number')),
                ('test_description', models.CharField(max_length=50, verbose_name='test_description')),
                ('project_num', models.CharField(max_length=50, verbose_name='project_num')),
                ('test_task_type', models.CharField(max_length=50, verbose_name='test_task_type')),
            ],
        ),
    ]
