# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectinfos',
            name='repository',
            field=models.CharField(max_length=500, verbose_name='code repository'),
        ),
    ]
