# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectinfos',
            name='verify_url',
            field=models.CharField(max_length=200, verbose_name='verify_url'),
        ),
    ]
