# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_collector', '0002_auto_20171108_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectinfos',
            name='submit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
