# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_collector', '0005_auto_20171109_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(default=None, max_length=10, verbose_name='jobid')),
                ('job_status', models.IntegerField(choices=[(0, 'complete'), (1, 'incomplete')], default=0, verbose_name='job status')),
                ('testcase', models.CharField(default=None, help_text='formate ${casename}:${result}', max_length=200, verbose_name='buildid')),
            ],
        ),
        migrations.AddField(
            model_name='collectinfos',
            name='bugid',
            field=models.CharField(default=None, max_length=200, verbose_name='bugid to gerrit'),
        ),
        migrations.AddField(
            model_name='collectinfos',
            name='filted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectinfos',
            name='from_verify_server_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collectinfos',
            name='repository',
            field=models.CharField(default=None, max_length=100, verbose_name='bugid to gerrit'),
        ),
        migrations.AlterField(
            model_name='collectinfos',
            name='status',
            field=models.IntegerField(choices=[(0, 'No submit'), (1, 'Submitted')], default=0, verbose_name='submit status'),
        ),
        migrations.AlterField(
            model_name='collectinfos',
            name='submit_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='submit time'),
        ),
        migrations.AlterField(
            model_name='collectinfos',
            name='submitted_result',
            field=models.IntegerField(choices=[(0, 'Submitted successfully'), (1, 'Submitted failed')], default=0, help_text='submitted task can be successfully or fail', verbose_name='submitted result'),
        ),
        migrations.AddField(
            model_name='testjob',
            name='collect_infos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_collector.CollectInfos'),
        ),
    ]
