# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_collector', '0006_auto_20171109_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectinfos',
            name='bugid',
            field=models.CharField(max_length=200, verbose_name='bugid to gerrit'),
        ),
        migrations.AlterField(
            model_name='collectinfos',
            name='repository',
            field=models.CharField(max_length=100, verbose_name='code repository'),
        ),
    ]
