# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_collector', '0007_auto_20171109_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectinfos',
            name='device_type',
            field=models.CharField(default=None, max_length=50, verbose_name='device type'),
        ),
        migrations.AlterField(
            model_name='collectinfos',
            name='submitted_fail_reason',
            field=models.CharField(help_text='submitted fail reason, if fail you can input some words mark it', max_length=100, verbose_name='submitted fail reason'),
        ),
        migrations.AlterField(
            model_name='testjob',
            name='testcase',
            field=models.CharField(default='default', help_text='formate ${casename}:${result}', max_length=200, verbose_name='buildid'),
        ),
    ]
